version: "3.8"

services:
  golang-app:
    container_name: golang-kafka
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - golang-mysql
      - golang-redis
    networks:
      - golang-kafka
    restart: always

  golang-mysql:
    container_name: golang-kafka-mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: template
      MYSQL_USER: worker
      MYSQL_PASSWORD: worker
    ports:
      - "3306:3306"
    volumes:
      - golang_kafka_mysql_data:/var/lib/mysql
    networks:
      - golang-kafka
    restart: always

  golang-redis:
    container_name: golang-kafka-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - golang-kafka
    restart: always

networks:
  golang-kafka:
    driver: bridge

volumes:
  golang_kafka_mysql_data:
