version: "3.8"

services:
  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
    networks:
      - golang-kafka
    restart: always
  mysql:
    image: mysql
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: template
      MYSQL_USER: '${mysql_A_DB_USER}'
      MYSQL_PASSWORD: '${mysql_A_DB_PASSWORD}'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - golang-kafka
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - golang-kafka
    restart: always

networks:
  golang-kafka:

volumes:
  mysql_data:
  redis_data:
